version: '3.8'

services:
  app:
    image: php:8.0-apache
    container_name: php-apache-container
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      
    ports:
      - "80:80"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    command: >
      bash -c "apt-get update &&
               apt-get install -y libpq-dev &&
               docker-php-ext-install pdo_pgsql &&
               apache2-foreground"
